######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 20 15:43:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += deck.h mainwindow.h table.h
SOURCES += deck.cpp main.cpp mainwindow.cpp table.cpp
RESOURCES += blackjack.qrc
CONFIG += QTestlib
